'use client';

import { useState, useEffect } from 'react';
import { gardenBacklogAI } from '@/app/lib/api-client';
import Modal from './Modal';

interface GardenerModalProps {
  onClose: () => void;
}

export default function GardenerModal({ onClose }: GardenerModalProps) {
  const [insights, setInsights] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchInsights = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await gardenBacklogAI();
      setInsights(data.insights);
    } catch {
      setError('The Gardener is resting. Please try again in a moment.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  return (
    <Modal title="🧑‍🌾 Backlog Garden Review" onClose={onClose}>
      <div className="flex flex-col gap-4 min-h-[300px]">
        {loading ? (
          <div className="flex-1 flex flex-col items-center justify-center gap-3 py-12">
            <div className="text-4xl animate-bounce">🚜</div>
            <p className="text-sm font-medium animate-pulse" style={{ color: 'var(--color-text-secondary)' }}>
              Tending to your tasks...
            </p>
          </div>
        ) : error ? (
          <div className="flex-1 flex flex-col items-center justify-center gap-3 py-12 text-center">
            <p className="text-sm text-red-500">{error}</p>
            <button 
              onClick={fetchInsights}
              className="text-xs font-bold underline text-indigo-500"
            >
              Try Again
            </button>
          </div>
        ) : (
          <>
            <div 
              className="flex-1 text-sm prose prose-slate max-w-none overflow-y-auto max-h-[60vh] p-4 rounded-lg border"
              style={{ background: 'var(--color-bg-secondary)', borderColor: 'var(--color-border)', color: 'var(--color-text)' }}
            >
              {/* Basic markdown-style rendering for the AI report */}
              <div className="whitespace-pre-wrap leading-relaxed">
                {insights}
              </div>
            </div>
            
            <div className="flex justify-between items-center pt-2">
              <p className="text-[10px] italic" style={{ color: 'var(--color-text-muted)' }}>
                Insights generated by AI co-pilot.
              </p>
              <button
                onClick={onClose}
                className="px-4 py-2 text-sm font-medium rounded-md text-white shadow-sm transition-all"
                style={{ backgroundColor: 'var(--color-primary)' }}
              >
                Got it, thanks!
              </button>
            </div>
          </>
        )}
      </div>
    </Modal>
  );
}
